### ISSUE TITLE
Difference between airport itlwm

### ISSUE THREAD

**Issue by seungjunProgramming** [a565109863/AirPortOpenBSD#4]
What's the difference between airportitlwm and this one?
Which one is better in which part???

**Comment by null2264** [comment]
I know this is an old issue, but in case someone stumbles upon this page:
- According to the author this one supports more hardware since it uses OpenBSD parts, but I'm not entirely sure... I couldn't test this part
- From my testing, it doesn't seem to have much difference in speed (since I only have access to 30Mbps internet, it probably doesn't affect my internet speed or something)
- In Ventura, it loads much faster than AirportItlwm at its current state (v2.2.0 - [`acc7ff9`](https://github.com/OpenIntelWireless/itlwm/commit/acc7ff95937b9fd8c347e9c5a4211eadb128723a), it even somehow loaded before I login to a user account)
- However, it still has the same issue as AirportItlwm, such as the location services and WiFi scan (https://github.com/OpenIntelWireless/itlwm/issues/799) issue, ~~you also still can't connect to hidden networks~~ (should be fixed in v2.3.0)
